#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p \
	/config/{log/spotweb,spotweb}

# copy spotweb retrieve file if not present in cron
[[ ! -f /etc/periodic/15min/retrieve ]] && \
cp /defaults/retrieve /etc/periodic/15min/retrieve

# link spotweb retrieve file if not present in config
[[ ! -f /config/spotweb/retrieve ]] && \
ln -s /etc/periodic/15min/retrieve /config/spotweb/retrieve

# logfiles needed by spotweb retrieve
[[ ! -f /config/log/spotweb/retrieve.log ]] && \
	touch /config/log/spotweb/retrieve.log

# permissions
chown -R abc:abc \
	/config
chmod -R 0644 /etc/logrotate.d
chmod -R +r /config/log
