#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p \
	/config/{log/spotweb,crontabs}

# copy crontab if needed
[[ ! -f /config/crontabs/root ]] && \
	cp /etc/crontabs/root /config/crontabs/root

# link user crontab
rm /etc/crontabs/root
ln -s /config/crontabs/root /etc/crontabs/root

# logfiles needed by spotweb retrieve
[[ ! -f /config/log/spotweb/retrieve.log ]] && \
	touch /config/log/spotweb/retrieve.log

# permissions
chown -R abc:abc \
	/config
chmod -R 0644 /etc/logrotate.d
chmod -R +r /config/log
