#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p \
	/config/{log/spotweb,spotweb}

# copy crontab and proxy defaults if needed
[[ ! -f /config/crontabs/root ]] && \
	cp /etc/crontabs/root /config/crontabs/

# import user crontabs
rm /etc/crontabs/*
cp /config/crontabs/* /etc/crontabs/

# logfiles needed by spotweb retrieve
[[ ! -f /config/log/spotweb/retrieve.log ]] && \
	touch /config/log/spotweb/retrieve.log

# permissions
chown -R abc:abc \
	/config
chmod -R 0644 /etc/logrotate.d
chmod -R +r /config/log
